/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fbf8fc",
        "surface-container-high": "#e9e7eb",
        "surface-tint": "#4e5e82",
        "surface-container-highest": "#e4e2e5",
        "inverse-primary": "#b6c6f0",
        "on-primary": "#ffffff",
        "outline": "#75777f",
        "secondary-container": "#6dfe9c",
        "inverse-surface": "#303033",
        "on-primary-container": "#8293ba",
        "tertiary-container": "#3f2600",
        "background": "#fbf8fc",
        "primary-container": "#1a2b4c",
        "surface": "#fbf8fc",
        "surface-dim": "#dbd9dd",
        "primary-fixed-dim": "#b6c6f0",
        "tertiary": "#241300",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#eabf8a",
        "on-secondary-fixed": "#00210c",
        "on-tertiary-container": "#b28c5b",
        "outline-variant": "#c5c6cf",
        "surface-container": "#efedf0",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffddb5",
        "secondary": "#006d36",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#364669",
        "on-background": "#1b1b1e",
        "secondary-fixed-dim": "#4de082",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005227",
        "inverse-on-surface": "#f2f0f3",
        "on-surface": "#1b1b1e",
        "secondary-fixed": "#6dfe9c",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#071b3b",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-fixed": "#2a1800",
        "on-secondary-container": "#007439",
        "on-surface-variant": "#44474e",
        "on-tertiary-fixed-variant": "#5e4117",
        "primary": "#031636",
        "surface-variant": "#e4e2e5",
        "surface-container-low": "#f5f3f6",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "16px",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "gutter": "24px",
        "base": "8px",
        "md": "24px",
        "sm": "12px",
        "xl": "64px",
        "lg": "40px",
        "container-max": "1440px"
      },
      fontFamily: {
        "body-sm": ["Public Sans", "sans-serif"],
        "label-sm": ["Public Sans", "sans-serif"],
        "display": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "h1": ["Public Sans", "sans-serif"],
        "h2": ["Public Sans", "sans-serif"],
        "h3": ["Public Sans", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.03em", "fontWeight": "600" }],
        "display": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "h1": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "h2": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "h3": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
