/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "surface-container": "#e5eeff",
        "tertiary-container": "#586076",
        "on-tertiary-fixed-variant": "#3f465c",
        "primary-fixed-dim": "#c3c0ff",
        "secondary-fixed-dim": "#ddb8ff",
        "secondary": "#831ada",
        "on-background": "#0b1c30",
        "on-tertiary-fixed": "#131b2e",
        "secondary-container": "#9e41f5",
        "on-tertiary-container": "#d4dbf5",
        "on-secondary-fixed-variant": "#6800b4",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#777587",
        "on-error-container": "#93000a",
        "tertiary": "#41485e",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#f0dbff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#213145",
        "surface": "#f8f9ff",
        "on-primary-fixed-variant": "#3323cc",
        "tertiary-fixed-dim": "#bec6e0",
        "error-container": "#ffdad6",
        "on-surface": "#0b1c30",
        "on-primary-container": "#dad7ff",
        "outline-variant": "#c7c4d8",
        "primary-fixed": "#e2dfff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "surface-bright": "#f8f9ff",
        "primary-container": "#4f46e5",
        "surface-tint": "#4d44e3",
        "tertiary-fixed": "#dae2fd",
        "on-surface-variant": "#464555",
        "on-secondary-fixed": "#2c0051",
        "error": "#ba1a1a",
        "surface-dim": "#cbdbf5",
        "surface-variant": "#d3e4fe",
        "surface-container-highest": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "inverse-primary": "#c3c0ff",
        "on-error": "#ffffff",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        "base": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "container-max": "1440px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "code-sm": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"]
      },
      fontSize: {
        "code-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["13px", {"lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg-mobile": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
